### ISSUE TITLE
creating meta_clean.json has bug

### ISSUE THREAD

**Issue by treksis** [Linaqruf/kohya-trainer#196] opened 2023-04-13 23:47 UTC
In LoRA fine-tuning colab notebook, I think there is a minor bug with meta_clean.json creation. 
Merged .json file (meta_cap.json + meta_cap_dd.json) is not saved into meta_clean.json but instead it overrides on meta_cap_dd.json.

https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb

<img width="1879" alt="image" src="https://user-images.githubusercontent.com/54779707/231905012-35d6c17c-827e-4bda-89bc-7a2411eaf03f.png">

<img width="1886" alt="image" src="https://user-images.githubusercontent.com/54779707/231905099-3efc2b2c-eb7b-4093-bedb-1f6cd244f2c1.png">

<img width="1880" alt="image" src="https://user-images.githubusercontent.com/54779707/231905134-742b2fff-5dfc-435a-87f3-eb1574459ea7.png">

**Comment by Linaqruf** [comment] 2023-04-14 09:03
Hi, this probably duplicate of https://github.com/Linaqruf/kohya-trainer/issues/194, and I want to tell you that I fixed the bug

**Closed** 2023-04-14 14:43 UTC
